/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLL.UsuarioControle;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Pichau
 */
public class FrameCadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Frame_CadastroUsuario
     */
    private final UsuarioControle controle;

    public FrameCadastroUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = new UsuarioControle(this);
        this.controle.CarreTabelaDeUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tex_UsuLogin = new javax.swing.JTextField();
        Tex_UsuSenha = new javax.swing.JTextField();
        Box_UsuDivisao = new javax.swing.JComboBox<>();
        Tex_UsuId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tex_UsuNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Bnt_UsuCadastrar = new javax.swing.JButton();
        Bnt_UsuExcluir = new javax.swing.JButton();
        Bnt_UsuLimpar = new javax.swing.JButton();
        Bnt_UsuEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Usuario = new javax.swing.JTable();
        Bnt_UsuCancelar = new javax.swing.JButton();
        Bnt_UsuAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE USUARIOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Dados Cadastrais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Divisão:");

        Box_UsuDivisao.setForeground(new java.awt.Color(0, 0, 0));
        Box_UsuDivisao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "CAIXA" }));

        Tex_UsuId.setEditable(false);
        Tex_UsuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tex_UsuIdActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nome:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tex_UsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_UsuDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tex_UsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tex_UsuId, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tex_UsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Tex_UsuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tex_UsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tex_UsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tex_UsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box_UsuDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15))
        );

        Bnt_UsuCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_UsuCadastrar.setText("Cadastrar");
        Bnt_UsuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_UsuCadastrarActionPerformed(evt);
            }
        });

        Bnt_UsuExcluir.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_UsuExcluir.setText("Excluir");
        Bnt_UsuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_UsuExcluirActionPerformed(evt);
            }
        });

        Bnt_UsuLimpar.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_UsuLimpar.setText("Limpar");
        Bnt_UsuLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_UsuLimparActionPerformed(evt);
            }
        });

        Bnt_UsuEditar.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_UsuEditar.setText("Editar");
        Bnt_UsuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_UsuEditarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Dados Cadastrais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        Table_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Table_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Login", "Senha", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_Usuario);

        Bnt_UsuCancelar.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_UsuCancelar.setText("Cancelar");
        Bnt_UsuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_UsuCancelarActionPerformed(evt);
            }
        });

        Bnt_UsuAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_UsuAtualizar.setText("Atualizar");
        Bnt_UsuAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_UsuAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bnt_UsuLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bnt_UsuAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bnt_UsuExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bnt_UsuCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Bnt_UsuEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(Bnt_UsuCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Bnt_UsuCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(Bnt_UsuExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(Bnt_UsuLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(Bnt_UsuAtualizar)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bnt_UsuCancelar)
                            .addComponent(Bnt_UsuEditar)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bnt_UsuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_UsuCancelarActionPerformed
        this.controle.Canselar();

    }//GEN-LAST:event_Bnt_UsuCancelarActionPerformed

    private void Bnt_UsuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_UsuCadastrarActionPerformed
        this.controle.cadastrar();
    }//GEN-LAST:event_Bnt_UsuCadastrarActionPerformed

    private void Bnt_UsuLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_UsuLimparActionPerformed
        this.controle.Limpar();
    }//GEN-LAST:event_Bnt_UsuLimparActionPerformed

    private void Bnt_UsuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_UsuEditarActionPerformed
        this.controle.EditarUsuario();

    }//GEN-LAST:event_Bnt_UsuEditarActionPerformed

    private void Bnt_UsuAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_UsuAtualizarActionPerformed
        this.controle.AtualizarUsuario();
    }//GEN-LAST:event_Bnt_UsuAtualizarActionPerformed

    private void Bnt_UsuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_UsuExcluirActionPerformed
        this.controle.ExcluirUsuario();
    }//GEN-LAST:event_Bnt_UsuExcluirActionPerformed

    private void Tex_UsuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tex_UsuIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tex_UsuIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnt_UsuAtualizar;
    private javax.swing.JButton Bnt_UsuCadastrar;
    private javax.swing.JButton Bnt_UsuCancelar;
    private javax.swing.JButton Bnt_UsuEditar;
    private javax.swing.JButton Bnt_UsuExcluir;
    private javax.swing.JButton Bnt_UsuLimpar;
    private javax.swing.JComboBox<String> Box_UsuDivisao;
    private javax.swing.JTable Table_Usuario;
    private javax.swing.JTextField Tex_UsuId;
    private javax.swing.JTextField Tex_UsuLogin;
    private javax.swing.JTextField Tex_UsuNome;
    private javax.swing.JTextField Tex_UsuSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton getBnt_UsuAtualizar() {
        return Bnt_UsuAtualizar;
    }

    public void setBnt_UsuAtualizar(JButton Bnt_UsuAtualizar) {
        this.Bnt_UsuAtualizar = Bnt_UsuAtualizar;
    }

    public JButton getBnt_UsuCadastrar() {
        return Bnt_UsuCadastrar;
    }

    public void setBnt_UsuCadastrar(JButton Bnt_UsuCadastrar) {
        this.Bnt_UsuCadastrar = Bnt_UsuCadastrar;
    }

    public JButton getBnt_UsuCancelar() {
        return Bnt_UsuCancelar;
    }

    public void setBnt_UsuCancelar(JButton Bnt_UsuCancelar) {
        this.Bnt_UsuCancelar = Bnt_UsuCancelar;
    }

    public JButton getBnt_UsuEditar() {
        return Bnt_UsuEditar;
    }

    public void setBnt_UsuEditar(JButton Bnt_UsuEditar) {
        this.Bnt_UsuEditar = Bnt_UsuEditar;
    }

    public JButton getBnt_UsuExcluir() {
        return Bnt_UsuExcluir;
    }

    public void setBnt_UsuExcluir(JButton Bnt_UsuExcluir) {
        this.Bnt_UsuExcluir = Bnt_UsuExcluir;
    }

    public JButton getBnt_UsuLimpar() {
        return Bnt_UsuLimpar;
    }

    public void setBnt_UsuLimpar(JButton Bnt_UsuLimpar) {
        this.Bnt_UsuLimpar = Bnt_UsuLimpar;
    }

    public JComboBox<String> getBox_UsuDivisao() {
        return Box_UsuDivisao;
    }

    public void setBox_UsuDivisao(JComboBox<String> Box_UsuDivisao) {
        this.Box_UsuDivisao = Box_UsuDivisao;
    }

    public JTable getTable_Usuario() {
        return Table_Usuario;
    }

    public void setTable_Usuario(JTable Table_Usuario) {
        this.Table_Usuario = Table_Usuario;
    }

    public JTextField getTex_UsuId() {
        return Tex_UsuId;
    }

    public void setTex_UsuId(JTextField Tex_UsuId) {
        this.Tex_UsuId = Tex_UsuId;
    }

    public JTextField getTex_UsuLogin() {
        return Tex_UsuLogin;
    }

    public void setTex_UsuLogin(JTextField Tex_UsuLogin) {
        this.Tex_UsuLogin = Tex_UsuLogin;
    }

    public JTextField getTex_UsuNome() {
        return Tex_UsuNome;
    }

    public void setTex_UsuNome(JTextField Tex_UsuNome) {
        this.Tex_UsuNome = Tex_UsuNome;
    }

    public JTextField getTex_UsuSenha() {
        return Tex_UsuSenha;
    }

    public void setTex_UsuSenha(JTextField Tex_UsuSenha) {
        this.Tex_UsuSenha = Tex_UsuSenha;
    }

    
}
