/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLL.VendaControle;
import java.beans.PropertyVetoException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Pichau
 */
public class FrameVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameVendas
     */
    private final VendaControle controle;

    public FrameVendas() throws PropertyVetoException {
        initComponents();
        this.controle = new VendaControle(this);
        this.controle.CarregarTabelaDeProdutos();
        this.controle.PreencherBoxCliente();
        this.controle.SetarData();
        this.controle.teste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Bnt_adicionarcomp = new javax.swing.JButton();
        Tex_venvalor = new javax.swing.JTextField();
        Tex_vennome = new javax.swing.JTextField();
        Tex_vencod = new javax.swing.JTextField();
        Tex_venquant = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Produtos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_itenspedido = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tex_data = new javax.swing.JTextField();
        Box_cliente = new javax.swing.JComboBox<>();
        Btn_fecharpe = new javax.swing.JButton();
        Btn_excluiriten = new javax.swing.JButton();
        Tex_quanttotaldeiten = new javax.swing.JTextField();
        Tex_valor_total_dos_peididos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BoxFormaPagamento = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LANÇAMENTO DE VENDAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Produto selecionado ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CODIGO:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NOME:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("VALOR:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("QUANTIDADE:");

        Bnt_adicionarcomp.setForeground(new java.awt.Color(0, 0, 0));
        Bnt_adicionarcomp.setText("ADICIONAR PEDIDO");
        Bnt_adicionarcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_adicionarcompActionPerformed(evt);
            }
        });

        Tex_venvalor.setEditable(false);

        Tex_vennome.setEditable(false);

        Tex_vencod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tex_vencodActionPerformed(evt);
            }
        });

        Tex_venquant.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tex_vencod, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tex_vennome, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tex_venvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tex_venquant, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bnt_adicionarcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tex_vencod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tex_vennome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tex_venvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Tex_venquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(Bnt_adicionarcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        Table_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Unidade", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Produtos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Table_ProdutosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Table_Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ProdutosMouseClicked(evt);
            }
        });
        Table_Produtos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Table_ProdutosComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Produtos);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)), "Intes do pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        Table_itenspedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Quantidade", "Valor Unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table_itenspedido);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CLIENTE:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DATA:");

        Tex_data.setEditable(false);

        Box_cliente.setForeground(new java.awt.Color(0, 0, 0));
        Box_cliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Box_clienteItemStateChanged(evt);
            }
        });
        Box_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_clienteActionPerformed(evt);
            }
        });

        Btn_fecharpe.setForeground(new java.awt.Color(0, 0, 0));
        Btn_fecharpe.setText("FECHAR PEDIDO");
        Btn_fecharpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_fecharpeActionPerformed(evt);
            }
        });

        Btn_excluiriten.setForeground(new java.awt.Color(0, 0, 0));
        Btn_excluiriten.setText("EXCLUIR ITEM");
        Btn_excluiriten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_excluiritenActionPerformed(evt);
            }
        });

        Tex_quanttotaldeiten.setEditable(false);

        Tex_valor_total_dos_peididos.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Quantidade Total de Itens:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Valor Total dos Pedidos:");

        BoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debito", "Credito" }));

        jLabel10.setText("FORMA DE PAGAMENTO:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Tex_data, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Box_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Btn_fecharpe)
                        .addGap(29, 29, 29)
                        .addComponent(Btn_excluiriten, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tex_valor_total_dos_peididos, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(Tex_quanttotaldeiten))))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Box_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tex_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Btn_fecharpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tex_quanttotaldeiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tex_valor_total_dos_peididos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(Btn_excluiriten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))))
        );

        setBounds(0, 0, 1508, 741);
    }// </editor-fold>//GEN-END:initComponents

    private void Box_clienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Box_clienteItemStateChanged

    }//GEN-LAST:event_Box_clienteItemStateChanged

    private void Box_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_clienteActionPerformed

    private void Tex_vencodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tex_vencodActionPerformed
          this.controle.AdicionarPedidoComLeitor();
    }//GEN-LAST:event_Tex_vencodActionPerformed

    private void Bnt_adicionarcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_adicionarcompActionPerformed

        this.controle.InserirItemNaTabela();
    }//GEN-LAST:event_Bnt_adicionarcompActionPerformed

    private void Btn_fecharpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_fecharpeActionPerformed
        this.controle.FecharPedido();

    }//GEN-LAST:event_Btn_fecharpeActionPerformed

    private void Btn_excluiritenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_excluiritenActionPerformed
        this.controle.ExcluirItem();
    }//GEN-LAST:event_Btn_excluiritenActionPerformed

    private void Table_ProdutosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Table_ProdutosAncestorAdded

    }//GEN-LAST:event_Table_ProdutosAncestorAdded

    private void Table_ProdutosComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Table_ProdutosComponentHidden

    }//GEN-LAST:event_Table_ProdutosComponentHidden

    private void Table_ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ProdutosMouseClicked
        this.controle.SelecionarProduto();
    }//GEN-LAST:event_Table_ProdutosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnt_adicionarcomp;
    private javax.swing.JComboBox<String> BoxFormaPagamento;
    private javax.swing.JComboBox<String> Box_cliente;
    private javax.swing.JButton Btn_excluiriten;
    private javax.swing.JButton Btn_fecharpe;
    private javax.swing.JTable Table_Produtos;
    private javax.swing.JTable Table_itenspedido;
    private javax.swing.JTextField Tex_data;
    private javax.swing.JTextField Tex_quanttotaldeiten;
    private javax.swing.JTextField Tex_valor_total_dos_peididos;
    private javax.swing.JTextField Tex_vencod;
    private javax.swing.JTextField Tex_vennome;
    private javax.swing.JTextField Tex_venquant;
    private javax.swing.JTextField Tex_venvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public JButton getBnt_adicionarcomp() {
        return Bnt_adicionarcomp;
    }

    public void setBnt_adicionarcomp(JButton Bnt_adicionarcomp) {
        this.Bnt_adicionarcomp = Bnt_adicionarcomp;
    }

    public JComboBox<String> getBox_cliente() {
        return Box_cliente;
    }

    public void setBox_cliente(JComboBox<String> Box_cliente) {
        this.Box_cliente = Box_cliente;
    }

    public JButton getBtn_excluiriten() {
        return Btn_excluiriten;
    }

    public void setBtn_excluiriten(JButton Btn_excluiriten) {
        this.Btn_excluiriten = Btn_excluiriten;
    }

    public JButton getBtn_fecharpe() {
        return Btn_fecharpe;
    }

    public void setBtn_fecharpe(JButton Btn_fecharpe) {
        this.Btn_fecharpe = Btn_fecharpe;
    }

    public JTable getTable_Produtos() {
        return Table_Produtos;
    }

    public void setTable_Produtos(JTable Table_Produtos) {
        this.Table_Produtos = Table_Produtos;
    }

    public JTable getTable_itenspedido() {
        return Table_itenspedido;
    }

    public void setTable_itenspedido(JTable Table_itenspedido) {
        this.Table_itenspedido = Table_itenspedido;
    }

    public JTextField getTex_data() {
        return Tex_data;
    }

    public void setTex_data(JTextField Tex_data) {
        this.Tex_data = Tex_data;
    }

    public JTextField getTex_quanttotaldeiten() {
        return Tex_quanttotaldeiten;
    }

    public void setTex_quanttotaldeiten(JTextField Tex_quanttotaldeiten) {
        this.Tex_quanttotaldeiten = Tex_quanttotaldeiten;
    }

    public JTextField getTex_valor_total_dos_peididos() {
        return Tex_valor_total_dos_peididos;
    }

    public void setTex_valor_total_dos_peididos(JTextField Tex_valor_total_dos_peididos) {
        this.Tex_valor_total_dos_peididos = Tex_valor_total_dos_peididos;
    }

    public JTextField getTex_vencod() {
        return Tex_vencod;
    }

    public void setTex_vencod(JTextField Tex_vencod) {
        this.Tex_vencod = Tex_vencod;
    }

    public JTextField getTex_vennome() {
        return Tex_vennome;
    }

    public void setTex_vennome(JTextField Tex_vennome) {
        this.Tex_vennome = Tex_vennome;
    }

    public JTextField getTex_venquant() {
        return Tex_venquant;
    }

    public void setTex_venquant(JTextField Tex_venquant) {
        this.Tex_venquant = Tex_venquant;
    }

    public JTextField getTex_venvalor() {
        return Tex_venvalor;
    }

    public void setTex_venvalor(JTextField Tex_venvalor) {
        this.Tex_venvalor = Tex_venvalor;
    }

    public JComboBox<String> getBoxFormaPagamento() {
        return BoxFormaPagamento;
    }

    public void setBoxFormaPagamento(JComboBox<String> BoxFormaPagamento) {
        this.BoxFormaPagamento = BoxFormaPagamento;
    }

    
    
}
