/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;
import  CONTROLL.RelatorioController;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Jailton
 */
public class FrameRalatorios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameRalatorios
     */
        
    private final RelatorioController controle;
    public FrameRalatorios() {
        initComponents();
        this.controle = new RelatorioController(this);
        this.controle.SetarIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextMes = new javax.swing.JFormattedTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("RELAORIO MENSAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DIGITE O MÊS E O ANO QUE DESEJA OBTER O RELATORIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 27, -1, -1));

        BtnConfirmar.setText("CONFIRMAR");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 160, -1, -1));

        jLabel2.setText("EX: 10-2021");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 85, -1, -1));

        try {
            TextMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextMes.setText("gfgdf");
        TextMes.setToolTipText("");
        TextMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMesActionPerformed(evt);
            }
        });
        getContentPane().add(TextMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 113, 92, -1));

        setBounds(650, 0, 535, 279);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
       this.controle.RelatorioMensal();
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void TextMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JFormattedTextField TextMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnConfirmar() {
        return BtnConfirmar;
    }

    public void setBtnConfirmar(JButton BtnConfirmar) {
        this.BtnConfirmar = BtnConfirmar;
    }

    public JFormattedTextField getTextMes() {
        return TextMes;
    }

    public void setTextMes(JFormattedTextField TextMes) {
        this.TextMes = TextMes;
    }

   

    

    


}
